### ISSUE TITLE
Description out of the screen

### ISSUE THREAD

**Issue by Reewarp** [Darkhax-Minecraft/Enchantment-Descriptions#100]
Hi,
I've tried the mod and when I'm interacting with villagers and watching enchanted books the description doesn't fit the screen as you can see here : https://imgur.com/a/y01x0dW

edit : didn't see your faq on discord before posting :
"**The tooltip is going off of the screen?**
This is a vanilla bug that only affects Fabric users of the mod. A third party mod such as ToolTipFix will be required to fix this issue. Forge users should not experience this issue as the fix is included with Forge itself. https://www.curseforge.com/minecraft/mc-mods/tooltipfix"

**Comment by Darkhax** [comment]
I am glad you worked it out on your own. I am updating this as a duplicate issue for my own records. 

Duplicate of #60
