### ISSUE TITLE
Please add support for these "fabric" mods

### ISSUE THREAD

**Issue by KMFrench1** [Darkhax-Minecraft/Enchantment-Descriptions#101]
Please add support for these "fabric" mods, if possible. They all have enchantment that dont have descriptions. 
1. Additional Additions
2. Bewitchment
3. Enderite mod
4. End Golbin Traders
5. Origins

Thanks

**Comment by Darkhax** [comment]
It is generally better to add support in the mod that is adding the enchantments. This allows the author to control the information being show and often results in players getting the most accurate and up to date information. It will also allow these mods to be compatible with other mods that add similar features.

I have begun the process of contributing support to those mods. Please follow each Pull Request to monitor the status of your request. 

- [x] [Additional Additions](https://github.com/Dqu1J/additionaladditions/pull/36)
- [x] [Bewitchment](https://github.com/MoriyaShiine/bewitchment/pull/266)
- [x] [Enderite mod](https://github.com/Nic4Las/Minecraft-Enderite-Mod/pull/61)
- [x] [End Golbin Traders](https://github.com/LimeAppleBoat/EndGoblinTraders/issues/12)
- [x] [Origins Fabric](https://github.com/apace100/origins-fabric/pull/512)
