### ISSUE TITLE
Support for Biome Makover

### ISSUE THREAD

**Issue by pewblaze** [Darkhax-Minecraft/Enchantment-Descriptions#102]
Support for Biome Makover would be awesome! 
https://www.curseforge.com/minecraft/mc-mods/biome-makeover

**Comment by Darkhax** [comment]
Hey, sorry for the late response. I prefer for mods to implement support on their end so they can have full control over the descriptions and can keep players updated with the most accurate information. I've submitted a Pull Request to the Biome Makeover mod that will add this support for them. Please track the Pull Request to monitor the status of your request. https://github.com/Lemonszz/Biome-Makeover/pull/90

**Comment by Darkhax** [comment]
Update: They have merged the Pull Request, meaning this is now supported on their end. Thanks again for the request.
