### ISSUE TITLE
Shift to display the descriptions

### ISSUE THREAD

**Issue by BrokenDawn627** [Darkhax-Minecraft/Enchantment-Descriptions#103]
Can you add this feature?
The descriptions only display when holding Shift.

**Comment by Laouke** [comment]
seconded, the text fills your whole inventory when looking at gear with lots of enchantments

**Comment by verlixis** [comment]
> seconded, the text fills your whole inventory when looking at gear with lots of enchantments

Agreed. Or optionally just show them when players have F3 + H on?

**Comment by janitor-raus** [comment]
Also looking forward to such a change. Having descriptions is nice, but the tooltips get blown up. It'd be nice to have them on-demand instead.

**Comment by ghost** [comment]
Hello, this would be really cool:)

**Comment by Adhulraj** [comment]
That would be very nice.

**Comment by ghost** [comment]
I would also love to have a custom key binding. User can then decide which key they prefer.

**Comment by Dr-WeiAL** [comment]
https://github.com/gliscowo/idwtialsimmoedm
Like this, hold down shift to display the description of the enchantment, which is very convenient
But it only has the fabric version, which is a pity

**Comment by Darkhax** [comment]
There is now a `"requireKeybindPress": false` option that allows you to require a keybind to be held to see descriptions. This option is false by default.

**Comment by Dr-WeiAL** [comment]
Oh...is 1.18.2 no longer updated? I see new features are only updated in 1.19.2

**Comment by Darkhax** [comment]
@Dr-WeiAL Older versions only receive bug fixes, security updates, or trivial changes.

**Comment by purejosh** [comment]
When will this modification be available for download? I have the latest version, 13.0.1, and it does not have this config option.

**Comment by Darkhax** [comment]
@purejosh The latest version on CurseForge is 13.0.3. https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3955030

**Comment by purejosh** [comment]
It's marked as an alpha release. That's why I'm unable to see it.

**Comment by purejosh** [comment]
Clicking "Minecraft 1.19" on the right hand side allowed me to see the Fabric 13.0.3 file I was looking for.
