### ISSUE TITLE
Enchant Descriptions crashes on forge 1.18.2 - 40.0.18

### ISSUE THREAD

**Issue by zachsai** [Darkhax-Minecraft/Enchantment-Descriptions#109]
https://pastebin.com/FNGpcBQJ
Enchant Descriptions crashes on forge 1.18.2 - 40.0.18

**Comment by Darkhax** [comment]
Bookshelf is a required dependency. You can find it [here](https://www.curseforge.com/minecraft/mc-mods/bookshelf).
