### ISSUE TITLE
Config setting to export list not working.

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Enchantment-Descriptions#11]
The setting in the configuration file to enable generating a list of enchantments without descriptions is not working.

I would like to add descriptions from the mods I've added to play with, is there something I can do?

**Comment by Darkhax** [comment]
Which version of the mod are you using? They should be logged to the console/log on game startup.

**Comment by ghost** [comment]
I am using the most recent version for Minecraft 1.12: "EnchantmentDescriptions-1.12.2-1.1.15"

Can you confirm for me where the mod would output the file?

**Comment by Darkhax** [comment]
It will be in your vanilla game log file. `.minecraft/logs/latest.log`, each line contains the text `Undefined enchantment from ` so you can search for them using that.

**Comment by ghost** [comment]
Thanks for the clarification, I wrongly assumed the list would be exported to the config folder or something.

To add descriptions myself, would the easiest way be to just open up the mod's jar file, and add to the _en_US.lang_ following the same format inside there?

**Comment by Darkhax** [comment]
Yes, changing the en_US.lang file or adding another one will allow custom entries. The most practical way would be to use something like ResourceLoader or CraftTweaker to accomplish this. If you're just adding new descriptions for modded enchantments you could also make a Pull Request, or post your changes on this issue, and I can add official support for those mods.
