### ISSUE TITLE
Needs bookshelf 13.0.6?

### ISSUE THREAD

**Issue by Grunglson** [Darkhax-Minecraft/Enchantment-Descriptions#110]
When I try to open the game I get a message saying I need bookshelf 13.0.6 but the latest version of bookshelf I can find is 12.0.23. Anyone now where to get 13.0.6 or is this a bug?

**Comment by Darkhax** [comment]
Hello,

13.x.x versions of Bookshelf are for MC 1.18.2 while 12.x.x versions are for MC 1.18.1. CurseForge is a bit annoying and does not show files sorted by version by default so the 13.x.x files are a bit lower in the file list. You can find all 13.x.x files [here](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/all?filter-status=1&filter-game-version=2020709689%3A9008).
