### ISSUE TITLE
Crash when loading client

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Enchantment-Descriptions#112]
EnchantmentDescriptions 10.0.2
Bookshelf 13.0.7
Fabric API 0.48.0+1.18.2
Fabric Loader 0.13.13

Other mods listed in crash report text file:
[crash-2022-04-05_17.43.18-server.txt](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/8419920/crash-2022-04-05_17.43.18-server.txt)

**Comment by ghost** [comment]
also tried with Bookshelf 13.0.8

**Comment by Darkhax** [comment]
Hello, thanks for reporting this issue. It looks like your configuration file is malformed and that is causing the crash. I will put out a new fix to prevent this from crashing again. If you've made changes to the config file, you should take another look to find the error. If you haven't made an edit you should delete the file and try again, a previous crash may have corrupted it.

**Comment by ghost** [comment]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'enchdesc'!
Exit Code: -1

I didnt touch any config files or anything, using latest fabric

**Comment by Darkhax** [comment]
@Kinami37 Please create a new issue report and upload your full log file there.
