### ISSUE TITLE
Some thoughts about visual

### ISSUE THREAD

**Issue by Disketaa** [Darkhax-Minecraft/Enchantment-Descriptions#117]
Greetings! In my opinion **dots** on the end of the every description-text are sort of rudiment. Minecraft never used dots in tooltips in the same way. 

Also maybe an one space from the start of the tooltip description would be nice to see! Like so, I attached:

![image](https://user-images.githubusercontent.com/76956762/170150153-7996692b-e2dd-4c19-8b0f-bd3434aca392.png)

**Comment by Darkhax** [comment]
Hello, thanks for the suggestion. I personally prefer tooltips with a period on the end. Normal vanilla tooltips are not sentences while this one is. 

I will consider adding a config option to allow indenting the tooltips.

**Comment by Darkhax** [comment]
There is now a `"indentSize": 0` option which allows you to specify an arbitrary number of indent spaces.
