### ISSUE TITLE
The mod works only client side

### ISSUE THREAD

**Issue by Lice2** [Darkhax-Minecraft/Enchantment-Descriptions#13]
EnchantmentDescriptions-1.14.4-1.3.3.jar

Forge Version 1.14.4-forge-28.1.36

As soon as the mod is on the server it crashes.
I do not have the crash log at the moment.

**Comment by Darkhax** [comment]
Thanks for reporting this issue. This is fixed in the next version of the mod which will be live on CurseForge soon.
