### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by Tishbyte** [Darkhax-Minecraft/Enchantment-Descriptions#131]
#107 
Don't know if it's worth reopening the issue, but I'm having the same issue. Was going to open a separate issue to add support for other mods and noticed the vanilla ones weren't even showing.
![image](https://user-images.githubusercontent.com/29070637/179294690-317c594b-6f6c-490b-a2db-e9e2e0ebe0d7.png)

Attached is the latest.log file.
[latest.log](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/9123435/latest.log)

It's probably a mod conflict, but it's not clear to me which one. Thanks for any help, but don't feel obligated since I know these kinds of issues are tricky.

**Comment by Darkhax** [comment]
Hello,

This is not the same issue as #107, as the description is showing in your image, it's just not being localized properly. The line `enchantment.minecraft.sharpness.desc` is the description key. 

I can not recreate this issue with the versions you are using, so this is likely a mod conflict or a pack configuration issue. Your pack log shows a LOT of errors that could potentially cause this however there is nothing immediately obvious that jumps out.

**Comment by Tishbyte** [comment]
Hi, just wanted to ask that you don't close this out just yet. I've been testing and I think I know which mods are conflicting. Will send here in the next couple of days.
Also, if there are other mods with enchantment descriptions to have added, would you like that opened as a separate issue?
Thanks!

**Comment by Darkhax** [comment]
Yes, if there is a mod that does not have support please open a new issue and I will work on adding the support. Using a new issue for each mod missing support is preferred.

**Comment by Tishbyte** [comment]
I found the conflicting mod. It was a combination of Origins, Show Me What You Got, and **RGPStats**.
RGPStats wasn't needed so I removed it and it revealed the enchantment descriptions. I'll submit new issues for the mods that don't have descriptions.
