### ISSUE TITLE
Support for Banci's enchantements

### ISSUE THREAD

**Issue by moninformateur** [Darkhax-Minecraft/Enchantment-Descriptions#135]
Greetings!
Would it be possible to add support for Banci's enchantements?

https://www.curseforge.com/minecraft/mc-mods/bancis-enchantments

Thank you!

**Comment by Darkhax** [comment]
Thanks for reaching out. Someone has already contacted the author of Banci's Enchantments about adding support for this mod. You can show your support for this change and track it's progress [here](https://www.curseforge.com/minecraft/mc-mods/bancis-enchantments/issues/1).
