### ISSUE TITLE
Support for BetterEnd, Enderite, Sonic Deflect, Aileron

### ISSUE THREAD

**Issue by GlorgusToe** [Darkhax-Minecraft/Enchantment-Descriptions#138]
Some mods that need support for this

End Veil (From BetterEnd)
https://www.curseforge.com/minecraft/mc-mods/betterend

Void Floating (From Enderite Mod)
https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-fabric

Sonic Deflect (From Sonic Deflect)
https://www.curseforge.com/minecraft/mc-mods/sonic-deflect

**Comment by egshels** [comment]
There's also Aileron's Smokestack and Cloudskipper enchants: https://www.curseforge.com/minecraft/mc-mods/aileron

**Comment by Darkhax** [comment]
Thank you for sharing all of these mods. I will start reaching out to them to get support implemented.

**Comment by Darkhax** [comment]
I've reached out to the mentioned mods to help them add support. You can track this on their GitHub repos.

- https://github.com/Nic4Las/Minecraft-Enderite-Mod/pull/61
- https://github.com/GitWither/sonic-deflect/pull/2
- https://github.com/quiqueck/BetterEnd/pull/55
- https://github.com/OrtusMC/Aileron/pull/4

~~@egshels I could not find the GitHub repo for aileron and reached out for more info on Discord. While I am open to adding descriptions on my end, it is generally best for everyone involved if the mod adding the enchantment also adds the description. This gives that mod more control over the description and leads to players having the most accurate and up to date information.~~

Edit: A PR for Aileron now exists.

**Comment by Darkhax** [comment]
All mods now have descriptions support 🎉
