### ISSUE TITLE
[Update] es_es translation improvement

### ISSUE THREAD

**Issue by Nekkok** [Darkhax-Minecraft/Enchantment-Descriptions#141]
Nothing against the original translators, but some enchantings were missing and some descriptions were not accurate too. I tried to improved the descriptions more accurately and I think I've got a really nice result. If there's some trouble or it would be better to contact with them, please let me talk with them.

Here's the new json, hope you appreciate it!
 
https://gist.github.com/kxkxrxtx/d470632f1a192b7ad23b9b032cc467f2

**Comment by Darkhax** [comment]
Thanks for the help, I will work on adding this soon.

**Comment by Darkhax** [comment]
The updated localizations should now be available in 1.18.2+. Thanks again.

**Comment by Nekkok** [comment]
Glad to help : )
