### ISSUE TITLE
Add Biome Makeover support

### ISSUE THREAD

**Issue by Tishbyte** [Darkhax-Minecraft/Enchantment-Descriptions#143]
Support for this mod: [https://www.curseforge.com/minecraft/mc-mods/biome-makeover](https://www.curseforge.com/minecraft/mc-mods/biome-makeover)
I found descriptions here: [https://biomemakeover.github.io/features/enchantments.html](https://biomemakeover.github.io/features/enchantments.html)
Thanks!

**Comment by Darkhax** [comment]
This mod already has support for enchantment descriptions. The code for this can be found [here](https://github.com/Lemonszz/Biome-Makeover/blob/1.19/common/src/main/resources/assets/biomemakeover/lang/en_us.json#L26-L36).

![image](https://user-images.githubusercontent.com/2250798/185015532-262a5308-4fd2-425d-9b13-d97046770e13.png)
