### ISSUE TITLE
Add Curses! Support

### ISSUE THREAD

**Issue by Tishbyte** [Darkhax-Minecraft/Enchantment-Descriptions#144]
Support for this mod: [https://www.curseforge.com/minecraft/mc-mods/curses](https://www.curseforge.com/minecraft/mc-mods/curses)
Descriptions are found in the above link as well.
Thanks!

**Comment by Darkhax** [comment]
I've opened a Pull Request to add support for this. You can track it here.

- https://github.com/HyperPigeon/Curses-/pull/3

**Comment by Darkhax** [comment]
The Curses team has accepted the pull request! This should be available after they release the update.
