### ISSUE TITLE
Add MC Dungeons Artifacts Support

### ISSUE THREAD

**Issue by Tishbyte** [Darkhax-Minecraft/Enchantment-Descriptions#146]
Support for this mod: [https://www.curseforge.com/minecraft/mc-mods/mcdar](https://www.curseforge.com/minecraft/mc-mods/mcdar)
I found descriptions here: [https://github.com/chronosacaria/MCDungeonsArtifacts/wiki/Enchantments](https://github.com/chronosacaria/MCDungeonsArtifacts/wiki/Enchantments)
Thanks!

**Comment by Darkhax** [comment]
I've opened a pull request for this. You can track it here.

- https://github.com/chronosacaria/MCDungeonsArtifacts/pull/19

**Comment by Darkhax** [comment]
Support has now been added to the original mod. Please wait for them to release an update.
