### ISSUE TITLE
Add MobSpecificEnchants Support

### ISSUE THREAD

**Issue by Tishbyte** [Darkhax-Minecraft/Enchantment-Descriptions#147]
Support for this mod: [https://www.curseforge.com/minecraft/mc-mods/mobspecificenchants](https://www.curseforge.com/minecraft/mc-mods/mobspecificenchants)
Descriptions are found in the above link as well.
Thanks!

**Comment by Darkhax** [comment]
I've opened a Pull Request to add support. You can track it here.

- https://github.com/NoComment1105/MobSpecificEnchants/pull/1

**Comment by Darkhax** [comment]
Support has now been added to the original mod. Please wait for them to release an update.
