### ISSUE TITLE
Add Netherited Support

### ISSUE THREAD

**Issue by Tishbyte** [Darkhax-Minecraft/Enchantment-Descriptions#148]
Support for this mod: [https://www.curseforge.com/minecraft/mc-mods/fabric-netherited](https://www.curseforge.com/minecraft/mc-mods/fabric-netherited)
Doesn't have a description that I can find, but a simple 'Fireproof' or 'Item won't burn in lava or fire' could work.
Thanks!

**Comment by Darkhax** [comment]
I've submitted a Pull Request to the netherited author that will add support. You can track that PR here: 

- https://github.com/polpg/Netherited/pull/5

**Comment by Darkhax** [comment]
Support has now been added to the original mod. Please wait for them to release an update.
