### ISSUE TITLE
Add ThonkUtil Support

### ISSUE THREAD

**Issue by Tishbyte** [Darkhax-Minecraft/Enchantment-Descriptions#149]
Support for this mod: [https://www.curseforge.com/minecraft/mc-mods/thonkutil](https://www.curseforge.com/minecraft/mc-mods/thonkutil)
I couldn't find any enchantment descriptions for this one.
Thanks!

**Comment by Darkhax** [comment]
This mod doesn't seem to add any enchantments to the game.

**Comment by Tishbyte** [comment]
Sorry to open this up, but it seems there is one: 
![image](https://user-images.githubusercontent.com/29070637/185734760-11cd24d3-af9b-4385-b6fe-894247c4f339.png)
