### ISSUE TITLE
Hide Description Function

### ISSUE THREAD

**Issue by CCCClear** [Darkhax-Minecraft/Enchantment-Descriptions#154]
I notice that this mod does not have the function to hide the description, that is, hold Shift to show the description. 
I think this is a good way to deal with too many enchants or too long descriptions. 
Sometimes the descriptions of the object's enchantment even covers the entire screen!

**Comment by Darkhax** [comment]
This mod already has this feature. Look in your config file for something like `requireKeybindPress`. The option is intentionally disabled by default because I prefer it the way it is.

**Comment by CCCClear** [comment]
Sorry to bother you, I am using 1.18.2 Forge 10.0.8 version, and this option is not included in the config. 
Is there a problem with my use?
![X)(NFXE 8W1YL0RPN((BZU8](https://user-images.githubusercontent.com/44665051/189028225-7e31fb81-7b4a-46b8-aeb7-88672177d880.png)

**Comment by Jer6776** [comment]
what is the keybind?
