### ISSUE TITLE
Hide Description Function for 1.18.2 Forge

### ISSUE THREAD

**Issue by CCCClear** [Darkhax-Minecraft/Enchantment-Descriptions#155]
Sorry to bother you, I am using 1.18.2 Forge 10.0.8 version, and this option is not included in the config. 
Is there a problem with my use?
![X)(NFXE 8W1YL0RPN((BZU8](https://user-images.githubusercontent.com/44665051/189028225-7e31fb81-7b4a-46b8-aeb7-88672177d880.png)

_Originally posted by @CCCClear in https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/154#issuecomment-1240175489_

**Comment by Darkhax** [comment]
I am mainly focusing on critical bug fixes and non-feature updates for older versions like 1.18.2 which is why you did not have this option. The option should be available now.
