### ISSUE TITLE
Support for Ma Enchants mod

### ISSUE THREAD

**Issue by JNCHGTR** [Darkhax-Minecraft/Enchantment-Descriptions#156]
Hello,

I would like to request support for Ma Enchants

https://www.curseforge.com/minecraft/mc-mods/ma-enchants

All:

NAME	LEVELS 	 AVAILABLE ON	 DESCRIPTION
Timeless	 0-1	 All	
Item with this enchant with not despawn after time when dropped on ground

Tools:

NAME	LEVELS 	TOOL	DESCRIPTION
Reinforced Tip	1-3	Pickaxe	Increase speed when mining obsidian (2x, 3x, 4x)
Stone Mending 	1-3	Pickaxe	Chance to restore 1 durability when mining stone (30%,60%,80%)
Lumberjack	0-1	Axe	Chop down trees at once. To activate hold "c" by default.
Momentum	0-1	Any tool 	Mining speed increases for each consecutive block of the same one.
Butchering	1-5	Axe	Deals extra damage to animals

Bow:

NAME	LEVELS 	DESCRIPTION
True Shot
0-1	 Arrows fired by this bow will not be affected by gravity
Quick Draw
1-3	 Draw bow faster
Floating
1-3	 Any mob struck with this enchant will be affected by the Shulker Effect Floating for 0.5-1.5 seconds
Paralysis
1-3	 Any mob struck with this will find themselves unable to move, jump, or attack for 0.5-1.5 seconds
Detonation
 1-3	Creates an explosion when hit a mob (does not destroy blocks)

Sword:

NAME	LEVELS 	DESCRIPTION
Combo
0-1	Increased damage with each successful strike, resets if it hits air or blocks.
Faster Attack
1-5	Increase attack speed
Lifesteal
0-1	Part of dealt damage restore your health
Ice Aspect
1-2	Slow down enemies for 1-2 seconds
Wisdom
1-5	Increase experience dropped by 0.2% each lvl

Armour:

NAME	LEVELS 	SLOT 	DESCRIPTION
Blazing Walker 	1-2	Boots	Similar to Minecraft Frost Walker but instead allows you to walk on lava
Step Assist	0-1	Boots	Gives you 1 block of step height
Night Vision	0-1	Helmet 	Gives you night vision potion effect
Multi Jump	1-2	Boots	Allow you to make 1 or 2 more jumps in air
Soft Fall	1-4	Boots	Eliminates falling damage, downside is that it gives exhaustion

New Curses:

NAME	LEVELS 	 AVAILABLE ON	DESCRIPTION
Breaking	1-3	 All	Item is breaking faster
Butterfingers 	0-1	Swords and Tools	Chance to drop your item when mining or attacking a mob
Aquaphobia	0-1	Armour	Slowly damage player when in water.
Death	0-1	Armour	Deals massive amount of damage when equipped or held in hand

Thanks in advance!

**Comment by Darkhax** [comment]
Thanks for the request. I will look into adding support for this soon.

**Comment by Darkhax** [comment]
It looks like Ma Enchants already has support for this mod.
