### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Cataratas** [Darkhax-Minecraft/Enchantment-Descriptions#159]
When requireKeybindPress is enabled it would make more sense to use `stack.isEnchanted()` instead of `stack.hasTag()` in the file EnchDescCommon, line 32.
It would avoid cases where an item has a tag but no enchantments.

with `stack.hasTag()`
![Captura de tela 2022-10-06 194642](https://user-images.githubusercontent.com/71784015/194433211-2e860a71-f1d8-4b90-9572-518f7768c80b.png)

with `stack.isEnchanted()`
![Captura de tela 2022-10-06 194504](https://user-images.githubusercontent.com/71784015/194433273-f09d3441-ba67-4aa6-8999-f1a38f43c628.png)

**Comment by Darkhax** [comment]
Thanks, this was an unintentional bug. Should be fixed in the next 1.19.2 version.
