### ISSUE TITLE
A way of Changing Description

### ISSUE THREAD

**Issue by notIkibo** [Darkhax-Minecraft/Enchantment-Descriptions#166]
I don't know, if there is any way e.g. through crafttweaker or kubejs to change the descriptions, but sometimes you also get the config for modded enchantments to change the values of them. Let's say instead of 30% of a thunder strike, you changed it to a third of the time(33%).

But the description still states "30%". Is there any way to alter the description?

**Comment by Darkhax** [comment]
You can change the descriptions for your pack by shipping a resource pack. The format is `enchantment.%namespace%.%id%.desc` so the enchantment `minecraft:sharpness` would be `enchantment.minecraft.sharpness.desc`.
