### ISSUE TITLE
Game crashes with 1.19.2 fabric

### ISSUE THREAD

**Issue by DarkCrystalll** [Darkhax-Minecraft/Enchantment-Descriptions#168]
[minecraft-exported-crash-info-2022-11-24T18-18-31.zip](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/10083497/minecraft-exported-crash-info-2022-11-24T18-18-31.zip)
I'm sure it's the problem of this mod, but I don't know what conflicts with it

**Comment by Darkhax** [comment]
Looking at the crash log this seems to be an issue with the Create mod.

**Comment by DarkCrystalll** [comment]
will it be fix? I really love both mod.

**Comment by Darkhax** [comment]
@DarkCrystalll The issue seems to be within the Create mod's code so you should report this to them and ask them about fixing it. If they identify any issues on my end I would be more than happy to look into fixing those.

**Comment by DarkCrystalll** [comment]
ok ok ,thank you !
