### ISSUE TITLE
Crash on server.

### ISSUE THREAD

**Issue by Sunekaer** [Darkhax-Minecraft/Enchantment-Descriptions#17]
forge-1.14.4-28.1.70
EnchantmentDescriptions-1.14.4-1.3.3

https://paste.dimdev.org/jesuxuqaso.rb

**Comment by Darkhax** [comment]
You're 5 builds behind latest. https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/2812154

**Comment by Sunekaer** [comment]
weird... twitch launcher didnt show that there was an update for this mod.
Thanks Dark!
