### ISSUE TITLE
[Forge 1.18.2] Text Formatting

### ISSUE THREAD

**Issue by INooBTooMuch** [Darkhax-Minecraft/Enchantment-Descriptions#170]
Is there a way to change the color of all the descriptions easily? 
And if there is would it also affect modded books or does that depend on the mod devs?

I tried using crafttweaker but some books (modded and not) don't change the tooltip color and it becomes quite complicated for me (casual players) so I was just wondering if there's an easier way.

Minecraft : 1.18.2
Forge : 40.1.85
Enchantment Descriptions : 10.0.9

**Comment by Darkhax** [comment]
Hello, using CraftTweaker to modify the tooltips is likely going to be the easiest and most reliable solution to this for now. I would recommend joining their Discord if you need help with your script. One potential way to do this in a script would be to loop through all tooltip entries and check if they are translatable, then check if the key starts with `enchantment.` and ends with `.desc`.
