### ISSUE TITLE
Where is the mods config?

### ISSUE THREAD

**Issue by SmallYii** [Darkhax-Minecraft/Enchantment-Descriptions#171]
I want to set it to hold down shift to display the description, but I can't find the relevant configuration.

**Comment by SmallYii** [comment]
Version fabric1.18.2

**Comment by Darkhax** [comment]
I am guessing you found it by yourself, but for anyone looking for this in the future, the config file is located in `./config/enchdesc.json`. You will need to run the game with the mod installed at least once for this file to be generated.
