### ISSUE TITLE
Impaling's description is inaccurate

### ISSUE THREAD

**Issue by NikkeKatski** [Darkhax-Minecraft/Enchantment-Descriptions#173]
![image](https://user-images.githubusercontent.com/77799777/207092072-3006404b-e30d-4ef4-9db0-63b89288e388.png)
The enchantment description states "players and aquatic mobs" when in reality it is only aquatic mobs that take additional damage.
As much as I wish Impaling was a good enchantment in java, only bedrock edition gets the damage benefit against players (provided that they are in water or rain however).

**Comment by Darkhax** [comment]
Thanks for letting me know, looks like I got it mixed up. Will have it fixed in a few minutes here.

**Comment by Darkhax** [comment]
This should now be fixed on 118.2, 1.19.2, and 1.19.3
