### ISSUE TITLE
Outdated Method Name

### ISSUE THREAD

**Issue by Kapitencraft** [Darkhax-Minecraft/Enchantment-Descriptions#180]
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.item.ItemStack.m_41619_()'
in EnchDescCommon line 33;

**Comment by Darkhax** [comment]
Please include your full log file.

**Comment by Kapitencraft** [comment]
[crash-2023-01-28_03.11.40-client.txt](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/10529579/crash-2023-01-28_03.11.40-client.txt)
There you go

**Comment by Darkhax** [comment]
When opening development related issue reports you should state that you are in a development environment in the issue. This will make things a lot clearer and save time with debugging your issues. Your errors here are related to how you are defining dependencies in the build.gradle file. You need to use fg.deobf for all mods, like I showed on the Bookshelf issue.
