### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by RandomGuy91** [Darkhax-Minecraft/Enchantment-Descriptions#182]
How do you add your own enchantment descriptions? I saw it on the read me but I have no idea how to do it. Can someone send a video or explain how to do it in depth? Thanks sooo much :)

**Comment by Darkhax** [comment]
Descriptions are loaded using resource packs. Simply add the entry to the language file in assets. You can find more info on this in the vanilla resource pack wiki.

**Comment by RandomGuy91** [comment]
Ok, thx :) (sry, I probably could have made that a lot less urgent...)
