### ISSUE TITLE
Support for 1.19.2

### ISSUE THREAD

**Issue by DiamondYoshi** [Darkhax-Minecraft/Enchantment-Descriptions#185]

**Comment by Darkhax** [comment]
Enchantment Descriptions already supports 1.19.2 for both Forge and Fabric, although I am guessing you noticed that right away and closed the issue. 

For future reference to anyone who stumbles upon this, you can find all 1.19.2 files [here](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/all?filter-status=1&filter-game-version=2020709689%3A9366).
