### ISSUE TITLE
Respiration enhancement off-screen

### ISSUE THREAD

**Issue by DTX3** [Darkhax-Minecraft/Enchantment-Descriptions#189]
I think because the Respiration enhancement description is longer than the rest, it always pushes the tooltip off-screen.

![IMG-0642](https://user-images.githubusercontent.com/59918994/233805427-7917e588-dd36-44c3-8739-a4c6f54553c2.jpg)

Fabric
1.19.2

**Comment by DTX3** [comment]
I just found a mod which fixes it. 

https://www.curseforge.com/minecraft/mc-mods/tooltipfix

**Comment by Darkhax** [comment]
Hello, thanks for taking the time to report this issue. This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug, like the mod you found. 

Duplicate of #60
