### ISSUE TITLE
add line breaks so that the descriptions dont force half of the box off screen

### ISSUE THREAD

**Issue by greatestdelilah** [Darkhax-Minecraft/Enchantment-Descriptions#190]
in their current state, enchantment descriptions straight up do not have line breaks, meaning any items on the left side of your screen just dont show up.
![image](https://user-images.githubusercontent.com/85757949/233871198-a18156a6-9978-43ee-9651-7875183662d9.png)

**Comment by greatestdelilah** [comment]
(this screenshot reaches to the edge of the screen btw, if it isnt clear)

**Comment by Darkhax** [comment]
Hello,

This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).
