### ISSUE TITLE
.

### ISSUE THREAD

**Issue by NidaimeHokage** [Darkhax-Minecraft/Enchantment-Descriptions#192]
.

**Comment by Darkhax** [comment]
This mod has nothing to do with flib or invcrafting. Report the issue to them.

**Comment by NidaimeHokage** [comment]
I'm so sorry, you are totally right. Thats kind of embarrassing now 😅 I had a issue prior to this one, maybe i will open another issue soon  :)
But thanks for the fast respone, i'm sorry again.
