### ISSUE TITLE
What a nice discription

### ISSUE THREAD

**Issue by DEMEMZEA** [Darkhax-Minecraft/Enchantment-Descriptions#198]
![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/86669215/5b2237a9-acde-4f65-9493-199459c7c063)

**Comment by pikipow** [comment]
well, ill contribute more to this issue.. without knowing what exactly is the above image.

this is what happens to me with "Tooltip Fix" mod installed
![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/16948665/037d6ad6-4595-4288-ab2f-2f4bce2e63fe)

**Comment by Darkhax** [comment]
You will have to ask the author of Creatures from the snow to provide a description in their language file. This was previously supported but I am guessing they reverted it unintentionally.
