### ISSUE TITLE
latest version not working

### ISSUE THREAD

**Issue by Zygus42** [Darkhax-Minecraft/Enchantment-Descriptions#2]
EnchantmentDescriptions-1.12.2-1.1.6
forge-1.12.2-14.23.1.2607-installer-win
no other mods

Not working at all.  There are no additional words on the tooltips, just the vanilla descriptions.

Version before this: EnchantmentDescriptions-1.12-1.0.4
Working fine.

**Comment by darkhax** [comment]
Thank you for the report. I can see the issue with the update. Currently late for me so I will have a fix out in the morning.

**Comment by darkhax** [comment]
This issue should be fixed now. Sorry for the delay.
