### ISSUE TITLE
Upgrade to 1.20.1, I found that version 1.20 does not work with 1.20.1 (including the Bookshelf module) thanks！

### ISSUE THREAD

**Issue by SoumiCN** [Darkhax-Minecraft/Enchantment-Descriptions#201]

**Comment by OBS3SS1ON** [comment]
x2 need 1.20.1

**Comment by Darkhax** [comment]
I am focusing on getting all my mods to 1.20 first before I start on 1.20.1. This will take a little bit, sorry for the delay.

**Comment by artginzburg** [comment]
I'm not a modder at all, so I'm not submitting a pull request, but there's a file called `fabric.mod.json` in the mod's .jar file. Inside, there's a `depends` > `minecraft` > `1.20`.

For now, I just changed it to `~1.20`, did the same for the [bookshelf-lib](https://modrinth.com/mod/bookshelf-lib) mod, and everything works perfectly on 1.20.1

**Comment by Darkhax** [comment]
The 1.20.1 update was put out a few days ago. https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files?version=1.20.1
