### ISSUE TITLE
Missing descriptions 

### ISSUE THREAD

**Issue by PinkLasagna03** [Darkhax-Minecraft/Enchantment-Descriptions#203]
From the mods shield+ https://www.curseforge.com/minecraft/mc-mods/shieldsplus and the grappling hook mod https://www.curseforge.com/minecraft/mc-mods/grappling-hook-mod

**Comment by Darkhax** [comment]
Thanks for the suggestion. I've added these to 17.0.2 for MC 1.20.1.
