### ISSUE TITLE
Inaccurate description for Respiration effect.

### ISSUE THREAD

**Issue by tyush** [Darkhax-Minecraft/Enchantment-Descriptions#204]
The Respiration enchantment description states that Respiration enhances your vision underwater. This aspect of the enchantment was removed in a [1.13 snapshot](https://minecraft.fandom.com/wiki/Java_Edition_18w08b#:~:text=no%20longer%20generate.-,Gameplay,-Changed%20natural%20water).

**Comment by Darkhax** [comment]
Thanks for letting me know. I've updated this description to be more accurate moving forward.
