### ISSUE TITLE
not compatible with hunter's return

### ISSUE THREAD

**Issue by SafeOfArsenal** [Darkhax-Minecraft/Enchantment-Descriptions#206]

**Comment by Darkhax** [comment]
Thanks for letting me know about this, I have updated the mod to add compatibility.

- 1.16.5 users should use 7.1.22+
- 1.18.2 users should use 10.0.14+
- 1.19.2 users should use 13.0.15+
- 1.19.4 users should use 15.0.4+
- 1.20.1 users should use 17.0.5+
