### ISSUE TITLE
[1.16.5] Not supported mods: missing descriptions

### ISSUE THREAD

**Issue by Fufciak** [Darkhax-Minecraft/Enchantment-Descriptions#207]
A list of mods I've encountered that lack enchantment descriptions:
- Origins(forge): Water Protection;
- Create: Potato Recovery, Capacity;
- Origins Accessiblities: Flying Protection;

**Comment by Darkhax** [comment]
Thanks for letting me know. The new [7.1.21 update](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/4736521) should now include these mods and a few others I noticed. Let me know if you see any other gaps in documentation in the future.
