### ISSUE TITLE
MC 1.16.5 - EnchDesc support for several mods with tons of enchants

### ISSUE THREAD

**Issue by JNCHGTR** [Darkhax-Minecraft/Enchantment-Descriptions#208]
Hey hey! I am requesting more support for other enchantment mods, if possible!

Minecraft version: 1.16.5

Here are the mods I am requesting support for <3

Illagers+ (7.5M downloads)
https://www.curseforge.com/minecraft/mc-mods/illagers

Organics 538K downloads)
https://www.curseforge.com/minecraft/mc-mods/organics

Mythic Botany (14.9M downloads)
https://www.curseforge.com/minecraft/mc-mods/mythicbotany

Nether Agriculture (1.7M downloads)
https://www.curseforge.com/minecraft/mc-mods/nether-agriculture

Grappling Hook Mod (16.2M downloads)
https://www.curseforge.com/minecraft/mc-mods/grappling-hook-mod

Pyromancer (3.3M downloads)
https://www.curseforge.com/minecraft/mc-mods/pyromancer

Pirates Armoury (89K downloads)
https://www.curseforge.com/minecraft/mc-mods/pirates-armoury

I'm adding the # of downloads on each to maybe help the team prioritize.

I would absolutely love for these to get added to Enchant Desc. I love the mod and the hard work everyone involved has done so far!

**Comment by Darkhax** [comment]
Thanks for letting me know about these mods. I haven't had time to go through them yet but I should have time within the next few days.

**Comment by Darkhax** [comment]
Support for all of these mods has been added in the [7.1.23 update](https://legacy.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/4757009). The file is currently being processed by CurseForge and will automatically be available once they're done with it.

**Comment by JNCHGTR** [comment]
You are an absolute legend! Imma peep the Patreon for this.
