### ISSUE TITLE
Shields+ enchant with no description

### ISSUE THREAD

**Issue by praydan** [Darkhax-Minecraft/Enchantment-Descriptions#215]
![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/18559602/a14da48a-314d-46c4-8ed7-c7fcd484e109)
Mod: https://www.curseforge.com/minecraft/mc-mods/shieldsplus
Mod description on curseforge is: Aegis (max V) (incompatible with Reinforced and Reflection): reduces damage taken by attacks when blocking by 10% per level

**Comment by Darkhax** [comment]
Thanks for letting me know. This has now been added in 17.0.9 for MC 1.20.1.
