### ISSUE TITLE
[1.20.1] Compat Request - Iron's RPG Tweaks

### ISSUE THREAD

**Issue by AetheriMC** [Darkhax-Minecraft/Enchantment-Descriptions#216]
Minecraft v1.20.1
Forge v47.2.4

Hello! Iron's RPG Tweaks mod has a feature which obfuscates the name of any enchantment found on items (including enchanting books) in "the wild" until the item is identified either using a scroll or by clicking on an enchanting table with the item.

The problem however, is that with Enchantment Descriptions installed, the description gives the enchantment away even though the name remains illegible. If possible, could the enchantment descriptions not be visible until the enchantment has been identified?

![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/64112227/cc89e063-cb5c-4edf-aedd-7aafbb2ab08f)

I find that hiding the enchantment's name until identified to be extremely immersive, and I believe it enriches every item with a new sense of worth.

Thank you for reviewing!

**Comment by Darkhax** [comment]
Thanks for the request, I agree this would be a great feature! I had a look at their code and apparently they already try to remove descriptions so I think this would be better classified as a bug on their end. You can find the specific code [here](https://github.com/iron431/rpg-tweaks/blob/b58c9dd49d689e0e2f1a1cc87185ee6838be580a/src/main/java/io/redspace/ironsrpgtweaks/enchantment_module/EnchantmentClientEvents.java#L52).

**Comment by AetheriMC** [comment]
Thank you for the feedback! I will go back to Iron and see if this is something they can address.
