### ISSUE TITLE
Create Stuff & Additions Compat

### ISSUE THREAD

**Issue by OminousDiscovery** [Darkhax-Minecraft/Enchantment-Descriptions#221]
![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/150559423/85765f37-a4cf-4962-9074-fac3b221f54b)

**Comment by Darkhax** [comment]
Thanks for letting me know, I've pushed updates for 1.16.5, 1.17.1, 1.18.2, 1.19.2, and 1.20.1
