### ISSUE TITLE
dependencies are needed when downloading from CurseForge but not show

### ISSUE THREAD

**Issue by CavalryHasArrived** [Darkhax-Minecraft/Enchantment-Descriptions#222]
Hi, I had to add the ''[Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf)''  library mod in order to use the mod but it's not listed as a ''[dependencie](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/relations/dependencies)'' when downloading on curseforge.
I donk know if it's cause i have other mods but everything worked fine until i installed ''**Enchantment Descriptions**'' without ''**Bookshelf**'' library mod.

**Comment by Darkhax** [comment]
Sorry for the confusion here, Bookshelf is a required dependency of Enchantment Descriptions and this has nothing to do with the other mods you have installed. 

The dependencies are defined correctly on CurseForge however the relations page that you linked to is currently not accurate. CurseForge will display the dependencies for the most recent file however older files or for alternative modloaders may have different dependencies. Their new redesigned site does not currently show per-file dependencies but you can still see them on the old legacy site if you're unsure. You can view this page by replacing the `www` with `legacy` in the URL. You can see an example [here](https://legacy.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/4911103).

I've made some changes to the files which should hopefully update the relations page in the future, however this is ultimately something CurseForge will need to fix in their user interface.
