### ISSUE TITLE
Support for 1.20.4

### ISSUE THREAD

**Issue by krafg** [Darkhax-Minecraft/Enchantment-Descriptions#223]
For now mod only loads until 1.20.2.

We wait for new versión.

Thanks.

**Comment by Crystal-Spider** [comment]
I second this

**Comment by Darkhax** [comment]
1.20.4 is now supported, you can find all 1.20.4 files [here](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files?page=1&pageSize=20&version=1.20.4)
