### ISSUE TITLE
Missing description for Hellfire enchantment (typo in file)

### ISSUE THREAD

**Issue by Matik1665** [Darkhax-Minecraft/Enchantment-Descriptions#225]
Hellfire enchantment from Create S&A is missing it's description. I did some digging and I found the description for this enchant. It is at the very end of the file and someone forgot to add ".desc" to name. Because of that it isn't showing in the game. 
Same issue with Impact enchant also from Create S&A.

![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/84602176/3aabf5d4-7d16-4d9c-8848-1ccd2c009d41)

![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/84602176/be2e63a0-f86b-4f13-b599-c1ba75e60518)

**Comment by Darkhax** [comment]
Thanks for letting me know. This should hopefully be fixed on every version it was added now.
