### ISSUE TITLE
improved exp mod suport

### ISSUE THREAD

**Issue by nightlord33** [Darkhax-Minecraft/Enchantment-Descriptions#226]
as in tittle how abaut adding descriptions for improved exp mod there is 59 enchanted books it wuld be very helpfull 
idk what is habitual space  or in all seriousnes enchants

**Comment by Darkhax** [comment]
Thanks for the suggestion. That's an insane amount of enchantments, the mod actually has 82 in the code. I've added descriptions for all of them, hope this helps.
