### ISSUE TITLE
[BUG] Unlisted Dependency for Bookshelf ?

### ISSUE THREAD

**Issue by MagpieMaydin** [Darkhax-Minecraft/Enchantment-Descriptions#229]
### Minecraft Version

1.20.1

### Mod Version

17.0.13

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

When I added this mod to a pack i was building the game had a mod loading error: "Mod enchdesc requires bookshelf 20 or above" However, there are no required dependencies listed on the Curseforge project page.

**Comment by Darkhax** [comment]
Hello, CurseForge lists dependencies on the individual file pages.  You can see that bookshelf is included [here](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/5015031/dependencies). You should always check the file specific dependencies as they can vary depending on the version and modloader.

**Comment by MagpieMaydin** [comment]
Your link makes it obvious.. but how is that link navigated to from the project description page? I went to files, and clicked on the one I Downloaded, but my screen doesn't show additional dependencies like yours.

[EDIT] it must be getting late here, I see now, the little "related projects link"

![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/22626869/c793d854-c871-4656-8daa-8fad2c7f2632)

So, you're right, but it's not very user-friendly. I much prefer the way everyone else does it, even if it's less exact. But thankyou for clearing that up for me; I am not the sharpest crayon in the box, and especially not after a few hours of binary searches to figure out why my 200+ modpack won't launch!

**Comment by Darkhax** [comment]
@MagpieMaydin Yeah I definitely wish they made it clearer. It used to be below the changelog until they moved it to it's own section. This issue keeps coming up, even more so after that change, so I will start including this info in my descriptions.
