### ISSUE TITLE
[FEEDBACK] To add translations in Spanish for these mods.

### ISSUE THREAD

**Issue by Arkathus** [Darkhax-Minecraft/Enchantment-Descriptions#230]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

I have created the Spanish translation for these mods:

Random Enchants 2
https://www.curseforge.com/minecraft/mc-mods/random-enchants-2

More Enchantments
https://www.curseforge.com/minecraft/mc-mods/more-enchantments_

And I would like it to be added to the official mod. I have used the 'es_es.JSON' file that I downloaded from this repository and added it. It works correctly without any issues. This is the file with the translation of the mods.

[es_es.json](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/14387872/es_es.json)

**Comment by Darkhax** [comment]
Thanks for localizing these entries. I've pushed an update for 1.20.1 and 1.20.4 which is currently being processed by CurseForge and will be available for everyone soon.
