### ISSUE TITLE
[FEEDBACK] Add BookShelf Dependency in Modrinth

### ISSUE THREAD

**Issue by kalinzange** [Darkhax-Minecraft/Enchantment-Descriptions#231]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Feedback
Add Bookshelf as Required Dependency in Modrinth ~ https://modrinth.com/mod/bookshelf-lib/

![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/38161086/ed8b7a39-6a4b-4e23-b4a8-10286b480069)

![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/38161086/4d46faa5-e6dc-4631-a569-5c60398ecad1)

**Comment by Darkhax** [comment]
Thanks, this should be fixed now.
