### ISSUE TITLE
[BUG] Misspelling

### ISSUE THREAD

**Issue by AphoticGoblin** [Darkhax-Minecraft/Enchantment-Descriptions#236]
### Minecraft Version

1.20.1

### Mod Version

17.0.14

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

![image](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/106140253/234dd170-2c3f-45c8-b0af-805d2bf2b391)
It spells breath here. Breath is a noun, the verb would be breathe.

**Comment by Darkhax** [comment]
Thank you for reporting this issue. It's been fixed for 1.20.1 and 1.20.4. New versions will automatically be uploaded to CurseForge soon.
