### ISSUE TITLE
[FEEDBACK] CurseForge Enviroment

### ISSUE THREAD

**Issue by Lucky-56** [Darkhax-Minecraft/Enchantment-Descriptions#237]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

The enviroment on CurseForge says "Client and Server" although this is a clientsided mod as stated in the description of this mod

**Comment by Darkhax** [comment]
This is set intentionally based on feedback and discussions with the CurseForge team and other creators. The mod loads fine on a server environment. If it does not you should file a separate issue with bug/crash info.

**Comment by Lucky-56** [comment]
oh okay, I thought it was on accident and never changed (I never uploaded a mod to CF so I don't know how it works)

**Comment by Lucky-56** [comment]
I mostly just want to more easily seperate which mods actually **NEED** to be on the server (for minimal load)
