### ISSUE TITLE
[QUESTION] Toggle this on/off?

### ISSUE THREAD

**Issue by Danekjovax** [Darkhax-Minecraft/Enchantment-Descriptions#238]
### Question

Is it feasible to add a mod option or better yet a hotkey binding to toggle these description on/off?  I don't find it helpful to see these expanded descriptions all the time, as it adds to the overall text "noise" of the overall GUI.  Thanks in advance.

**Comment by Darkhax** [comment]
You can enable the `requireKeybindPress` option in the config file.

**Comment by Danekjovax** [comment]
> You can enable the `requireKeybindPress` option in the config file.

 I found the option in "enchdesc.json".  Toggled it, then restarted my client, but in-game I don't see where the keybind is, and no options come up for this mod in the mod options screen.  Please advise.

**Comment by Danekjovax** [comment]
> > You can enable the `requireKeybindPress` option in the config file.
> 
> I found the option in "enchdesc.json". Toggled it, then restarted my client, but in-game I don't see where the keybind is, and no options come up for this mod in the mod options screen. Please advise.

Ok, it allows holding SHIFT to see the descriptions?  If that's it, I am seeing that behavior.  Thanks again.
