### ISSUE TITLE
Bug with spanish translations [1.12.2]

### ISSUE THREAD

**Issue by slinkybass** [Darkhax-Minecraft/Enchantment-Descriptions#24]
Spanish translations are not loading due to an error in the lang file.

The string "% s" is misspelled: "% s".

**Comment by Darkhax** [comment]
Thanks, I have pushed updates for 1.12.2, 1.14.4 and 1.15.2

**Comment by slinkybass** [comment]
Can you update it in Curseforge? Thanks!
