### ISSUE TITLE
[issue] minecraft crashed with this mod, when i installed java 16!

### ISSUE THREAD

**Issue by tola-gerasim23** [Darkhax-Minecraft/Enchantment-Descriptions#241]
### Minecraft Version

1.17.1

### Mod Version

8.17.1

### Mod Loader

Forge

### What environment are you running the mod in?

Don't Know / Not Applicable

### Issue Description

this is list of mods:
![2024-06-17_12-46-58](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/173048761/2e610b59-7160-450f-98cb-0b9a4350a1aa)
![2024-06-17_12-47-00](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/173048761/54ca6d3a-7911-473a-afb5-b602bc2be42d)

i'm playing in this map:
![2024-06-17_12-48-21](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/173048761/ad10a3cf-4555-4489-bda6-e4daead44b70)

**Comment by OminousDiscovery** [comment]
who stills plays on 1.17.1...

**Comment by Darkhax** [comment]
Please ignore that other comment, they are not involved in the development of Enchantment Descriptions and I don't know why they commented here if they had nothing to contribute to the discussion. 

As for your crash, if the game crashes you should always include a crash log with your report. A crash log is always generated and contains the necessary info to diagnose the issue. Based on the limited information you provided, I am guessing you didn't install the [Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/all?page=1&pageSize=20&version=1.17.1&gameVersionTypeId=1) mod which is a dependency of enchantment descriptions. If you haven't installed this mod please install it and let me know if the game stops crashing.
