### ISSUE TITLE
[QUESTION] <title>Is version 1.21 Fabric Korean version also available?

### ISSUE THREAD

**Issue by pil0lo** [Darkhax-Minecraft/Enchantment-Descriptions#242]
### Question

Is version 1.21 Fabric Korean version also available?

무기 관련 (weapon)

날카로움(검, 도끼에 적용 가능. 단, 도끼는 책과 모루를 사용하는 경우에만 가능)
설명 : 모든 몹을 상대로 추가 데미지. 강타나 살충과는 명령어를 사용하지 않는 이상 중첩이 불가능.
등급별 피해 증가량
I : 1
II : 1.5
III : 2
IV : 2.5
V : 3

강타(검, 도끼에 적용 가능. 단, 도끼는 책과 모루를 사용하는 경우에만 가능)
설명 : 언데드 계열(좀비, 스켈레톤, 피그맨, 팬텀, 위더) 몹을 상대로 추가 데미지. 날카로움과 살충과는 명령어를 사용하지 않는 이상 중첩 불가능.
등급별 대 언데드 피해 증가량
I : 2.5
II : 5
III : 7.5
IV : 10
V : 12.5

살충(검, 도끼에 적용 가능. 단, 도끼는 책과 모루를 사용하는 경우에만 가능)
설명 : 벌레 계열(거미, 동굴거미, 엔더마이트, 좀벌레, 벌) 몹을 상대로 추가 데미지 및 속도 감소 IV 부여. 날카로움과 강타와는 명령어를 사용하지 않는 이상 중첩 불가능.
등급별 대 벌레 피해 증가량 및 속도 감소 지속량
I : 2.5, 1~1.5초
II : 5, 1~2초
III : 7.5, 1~2.초
IV : 10, 1~3초
V : 12.5, 1~3.5초

밀치기(검에 적용 가능)
설명 : 근접공격시 밀쳐내는 거리 증가.
등급별 거리 증가율
I : 3 증가
II : 6 증가

 

발화(검에 적용 가능)
설명 : 근접공격시 대상에게 불을 붙인다.
등급별 지속 시간
I : 4초
II : 8초

휘몰아치는 칼날(검에 적용 가능)
설명 : 검으로 공격했을 시 주변에 주는 쓸어내기 피해량 증가
등급별 피해량
I : 직격 피해량의 50% + 1
II : 직격 피해량의 66% + 1
III : 직격 피해량의 75% + 1

약탈(검에 적용 가능)
설명 : 처치한 몹의 아이템 드랍률 및 최대 드랍량 증가
등급별 증가율
I : 일반 아이템 드롭 0-1개 증가, 드문 아이템이 드롭되지 않을 경우 50% 확률로 드롭, 희귀 아이템 드롭 확률 +1%, 몹이 장착하고 있던 장비 아이템 드롭 확률 +1%
II : 일반 아이템 드롭 0-2개 증가, 드문 아이템이 드롭되지 않을 경우 66% 확률로 드롭, 희귀 아이템 드롭 확률 +2%, 몹이 장착하고 있던 장비 아이템 드롭 확률 +2%
III : 일반 아이템 드롭 0-3개 증가, 드문 아이템이 드롭되지 않을 경우 75% 확률로 드롭, 희귀 아이템 드롭 확률 +3%, 몹이 장착하고 있던 장비 아이템 드롭 확률 +3%

힘(활에 적용 가능)
설명 : 활의 공격력 상승
등급별 증가율
I : 50%
II : 75%
III : 100%
IV : 125%
V : 150%

밀어내기(활에 적용 가능)
설명 : 활에 맞은 대상을 밀어낸다.
등급별 증가율
I : 3~4 증가
II : 7 증가

화염(활에 적용 가능)
설명 : 불화살을 발사하고, 피격된 대상은 불이 붙는다.

무한(활에 적용 가능)
설명 : 화살이 한 개라도 있으면 무한으로 발사가 가능해진다. 단, 무한활로 발사한 화살은 회수 불가능.

빠른 장전(쇠뇌에 적용 가능)
설명 : 쇠뇌의 재장전 시간이 감소한다. 등급은 I~III까지 있다.

다중 발사(쇠뇌에 적용 가능)
설명 : 한 번의 발사로 화살을 부채꼴 모양으로 세 발 쏠 수 있다.

관통(쇠뇌에 적용 가능)
설명 : 화살이 엔디티나 방패를 관통할 수 있다.

등급별 관통 가능 수
I : 1번
II : 2번
III : 3번
IV : 4번
V : 5번

충절(삼지창에 적용 가능)
설명 : 삼지창을 던지면 되돌아온다. 등급은 I부터 III까지 있으며, 등급이 높을수록 돌아오는 시간이 감소한다.

찌르기(삼지창에 적용 가능)
설명 : 수생(가디언, 엘더가디언, 돌고래, 거북, 물고기, 오징어) 몹을 상대로 추가 데미지
등급별 추가 피해량
I : 2.5
II : 5
III : 7.5
IV : 10
V : 12.5

급류(삼지창에 적용 가능)
설명 : 삼지창을 못 던지게 되나 비가 오거나 수중에서 삼지창을 던질 경우 빠른 속도로 돌진한다. 등급은 I~III까지 있으며, 높은 등급일수록 더 멀리까지 질주한다.

집전(삼지창에 적용 가능)
설명 : 삼지창을 던져서 떨어진 곳에 번개가 치게 만든다. 단, 폭풍우가 오는 상황에서만 가능하고 돼지, 주민, 크리퍼에게 던질 경우 좀비피그맨, 마녀, 충전된 크리퍼로 변신하는 대참사가 벌어지니 주의할 것.

 

방어구 관련(armor)

보호(모든 방어구에 적용 가능)
설명 : 공허, 굶주림 등을 제외한 모든 피해량 감소
등급별 피해량 감소
I : 4%
II : 8%
III : 12%
IV : 16%

화염으로부터 보호(모든 방어구에 적용 가능)
설명 : 화염, 블레이즈, 용암으로부터 받는 데미지 및 불타는 시간 감소
등급별 감소량
I : 화염 피해량 8%, 불타는 시간 15%
II : 화염 피해량 16%, 불타는 시간 30%
III : 화염 피해량 24%, 불타는 시간 45%
IV : 화염 피해량 32%, 불타는 시간 60%

폭발로부터 보호(모든 방어구에 적용 가능)
설명 : 폭발로 받는 데미지 및 넉백 감소
등급별 감소량
I : 폭발 피해량 8%, 넉백 15%

II : 폭발 피해량 16%, 넉백 30%
III : 폭발 피해량 24%, 넉백 45%
IV : 폭발 피해량 32%, 넉백 60%

원거리 공격으로부터 보호(모든 방어구에 적용 가능)
설명 : 화살, 삼지창 등 투사체로 받는 데미지 감소
등급별 감소량
I : 투사체 피해량 8%
II : 투사체 피해량 16%
III : 투사체 피해량 24%
IV : 투사체 피해량 32%

가시(흉갑, 바지에 적용 가능. 투구와 부츠는 책과 모루로만 적용 가능)
설명 : 적의 공격에 반응해서 반사 피해를 입힌다.
등급별 확률 및 데미지
I : 15% 확률로 공격자에게 1~4 피해를 입힘. 피해를 입히면 추가 내구도 소모 3, 입히지 않으면 1
II : 30% 확률로 공격자에게 1~4 피해를 입힘. 피해를 입히면 추가 내구도 소모 3, 입히지 않으면 1
III : 45% 확률로 공격자에게 1~4 피해를 입힘. 피해를 입히면 추가 내구도 소모 3, 입히지 않으면 1
IV : 60% 확률로 공격자에게 1~4 피해를 입힘. 피해를 입히면 추가 내구도 소모 3, 입히지 않으면 1

호흡(투구에 적용 가능)
설명 : 산소량 및 질식으로 인한 피해 간격 증가
등급별 능력치
I : 호흡 지속시간 15초, 50% 확률로 질식 피해 방어
II : 호흡 지속시간 30초, 66% 확률로 질식 피해 방어
III : 호흡 지속시간 45초, 75% 확률로 질식 피해 방어

친수성(투구에 적용 가능)
설명 : 수중 작업속도 상승

가벼운 착지(부츠에 적용 가능)
설명 : 추락 데미지 감소
등급별 감소량
I : 추락 피해량 12% 감소
II : 추락 피해량 24% 감소
III : 추락 피해량 36% 감소
IV : 추락 피해량 48% 감소

물갈퀴(부츠에 적용 가능)
설명 : 수중 이동속도 감소 상쇄
등급별 능력치
I : 감소 효과 33% 상쇄
II : 감소 효과 66% 상쇄
III : 감소 효과 100% 상쇄

 

도구 관련

효율(삽, 곡괭이, 도끼에 적용 가능. 가위는 책과 모루로만 가능)
설명 : 작업력 상승, 도끼의 방패 무력화 확률 상승(자바에디션 한정)
등급별 능력치
I : 작업 속도 +2, 방패 무력화 확률 5% 상승
II : 작업 속도 +5, 방패 무력화 확률 10% 상승
III : 작업 속도 +10, 방패 무력화 확률 15% 상승
IV : 작업 속도 +17, 방패 무력화 확률 20% 상승
V : 작업 속도 +26, 방패 무력화 확률 25% 상승

섬세한 손길(삽, 곡괭이, 도끼에 적용 가능)
설명 : 블록을 원형 그대로 채취 가능

내구성(무기, 방어구, 삽, 도끼, 곡괭이, , 낚싯대에 적용 가능. 괭이, 가위, 당근낚싯대, 부싯돌과 부시, 방패, 겉날개는 책과 모루로만 가능)
설명 : 내구도 감소 확률 하락
등급별 능력치
I : 도구 50%, 방어구 80% 확률로 내구도 감소
II : 도구 33%, 방어구 73.3% 확률로 내구도 감소
III : 도구 25%, 방어구 70% 확률로 내구도 감소

행운(도끼, 곡괭이, 삽에 적용 가능)
설명 : 블록을 파괴했을 경우 드랍하는 아이템 개수 및 확률 증가. I~III까지 등급이 있다.

바다의 행운(낚싯대에 적용 가능)
설명 : 낚는 아이템의 희귀도 상승
등급별 능력치
I : 쓰레기를 낚을 확률 1.95% 감소, 보물을 낚을 확률 2.1% 증가, 물고기를 낚을 확률 0.15% 감소.
II : 쓰레기를 낚을 확률 3.9% 감소, 보물을 낚을 확률 4.2% 증가, 물고기를 낚을 확률 0.3% 감소.
III : 쓰레기를 낚을 확률 5.85% 감소, 보물을 낚을 확률 6.3% 증가, 물고기를 낚을 확률 0.45% 감소.

미끼(낚싯대에 적용 가능)
설명 : 낚시에 걸리는 시간 감소
등급별 능력치
I : 미끼를 물 때까지 간격 5초 감소
II : 미끼를 물 때까지 간격 10초 감소
III : 미끼를 물 때까지 간격 15초 감소

 

보물 관련

차가운 걸음(책과 모루를 이용해 부츠에만 적용 가능)
설명 : 밟고 있는 주변 물을 일시적으로 얼음으로 만들고, 마그마 블록 위에서 데미지를 입지 않는다.
등급별 능력치
I : 얼음 생성 반경 2 증가
II : 얼음 생성 반경 3 증가

수선(책과 모루를 이용해 내구도를 소모하는 모든 아이템에 적용 가능)
설명 : 경험치를 소비해서 내구도를 회복한다.

귀속 저주(방어구에만 적용 가능)
설명 : 귀속 저주가 걸린 방어구를 입으면 죽거나 갑옷이 파손될 때까지 절대 벗을 수 없다. 라모님 왕관에다가 걸어버릴까

소실 저주(모루와 책으로 붙일 수 있는 모든 아이템에 적용 가능)
설명 : 소실 저주가 걸린 아이템을 지닌 상태에서 죽으면 아이템이 사라진다.

**Comment by Darkhax** [comment]
Hello, this mod has not been updated to 1.21 yet. It only supports up to 1.20.4 for now. If you would like to help localize this mod to korean after it is ported, please make an update to the [`ko_kr.json`](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/blob/1.20.4/common/src/main/resources/assets/enchdesc/lang/ko_kr.json) file and I will happily accept it.

The 1.21 version will be soon, I just have a lot of work I need to do before I move on.
