### ISSUE TITLE
doesnt show[BUG] <title>

### ISSUE THREAD

**Issue by MrSquirrel250** [Darkhax-Minecraft/Enchantment-Descriptions#243]
### Minecraft Version

1.20.4

### Mod Version

most recent

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

I have all things downloaded but nothing shows =(

**Comment by Darkhax** [comment]
Please double check that you have installed everything correctly. If you install Forge files on Fabric accidentally they will not load. If you still think you have set up everything correctly please upload your latest.log file.
