### ISSUE TITLE
[BUG] desc doesn't show with custom Fullname

### ISSUE THREAD

**Issue by FOOLSIX** [Darkhax-Minecraft/Enchantment-Descriptions#244]
### Minecraft Version

1.19.2

### Mod Version

13.0.20

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

I'm a new modder and making my enchantment mod.
For some reason, I override Enchantment#getFullname and modify the displayed name, and then found that the desc of these enchantments is not displayed.
All other enchantments whose names have not been changed are ok.
[My Code](https://github.com/FOOLSIX/FancyEnchantments/blob/main/src/main/java/com/foolsix/fancyenchantments/enchantment/EssentiaEnch/IgnisEnchantment.java)
![info](https://github.com/user-attachments/assets/d832c90a-3efd-490e-9e44-a6151aa1cfc3)
(My JEI plugin reads and shows desc correctly, but this mod does not)

**Comment by Darkhax** [comment]
Hello, this mod relies on the enchantment name to locate where the description should be inserted. In your case the curse prefix breaks this logic so it can't find where to insert the description. It's not an ideal approach but it's from before mixins were widely used. You can see the code [here](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/blob/1.20.4/common/src/main/java/net/darkhax/enchdesc/EnchDescCommon.java#L47-L61). This will be improved in 1.21 but I am not sure about 1.19.2.

**Comment by FOOLSIX** [comment]
Thank you for your prompt reply. I understand now, my prefix has become the contents of this line's Component, and the description ID has been placed in the siblings. Is it possible for this to be improved in versions 1.19.2 and 1.20.1? Or it would be better if I changed the prefix to a suffix？

**Comment by Darkhax** [comment]
I just released a new update for 1.20.1. If this fix works I can backport it to 1.19.2 as well.

**Comment by FOOLSIX** [comment]
It seems that the build was not successful, 1.20.1 update was not released.But the code looks fine

**Comment by Darkhax** [comment]
Thanks, looks like some bad code snuck into that commit. It's fixed and available now as 17.1.18.

**Comment by FOOLSIX** [comment]
I tested it. It looks like it's working well. Thank you for your support.    <3

![desc](https://github.com/user-attachments/assets/8e8d5f3c-f21b-4f33-9256-ec087958cca6)
