### ISSUE TITLE
[FEEDBACK] 1.21 Support

### ISSUE THREAD

**Issue by WollenMoth** [Darkhax-Minecraft/Enchantment-Descriptions#245]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Feedback

I´ve never tried the project, but it seems very useful

**Comment by Darkhax** [comment]
It's in the works but it will take a bit. This is my statement on 1.21 from Discord. 
![image](https://github.com/user-attachments/assets/fdb4799f-e96b-42cd-b66d-424ab721fbdc)
