### ISSUE TITLE
Add the ability to hide the line "Enchantment" and "Added by"

### ISSUE THREAD

**Issue by TheDirectorX** [Darkhax-Minecraft/Enchantment-Descriptions#25]
You can make it so that if a book has one enchantment, the **"Enchantment"** field is automatically hidden, because then the name is duplicated. Or add the ability to _enable_ or _disable_ these lines via **config**. Also with **"Added by"**, some mods add the ability to view which mod this item is from, such as `Mod Name Tooltip`.
![image](https://user-images.githubusercontent.com/43481085/76687678-0f624b80-6648-11ea-9214-5cd11c9ce246.png)

**Comment by Darkhax** [comment]
Thanks for the suggestion. In the new version of the mod the name of the enchantment has been removed and the description is inserted below the enchantment's pre-existing name. 

Config options were added to turn off the added by text, and several other aspects of the tooltip such as the keybind activation requirement and whether or not non-book items can display the tooltip.
