### ISSUE TITLE
Port for 1.21

### ISSUE THREAD

**Issue by hoffmannE** [Darkhax-Minecraft/Enchantment-Descriptions#252]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Feedback

Id like to suggest a port for **1.21** as 1.21.1. I hope this is possible to make. Thank u in advance.

**Comment by Darkhax** [comment]
Hello, 1.21.1 is already supported. The base 1.21 version will not be supported as it contains security vulnerabilities and should not be supported.
