### ISSUE TITLE
[BUG] <title> enchantment descriptions not worked 1.21.1

### ISSUE THREAD

**Issue by lazkopat3718** [Darkhax-Minecraft/Enchantment-Descriptions#254]
### Minecraft Version

1.21.1

### Mod Version

52.0.16

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

The mod does not work even though all plugins are installed

**Comment by lazkopat3718** [comment]
https://pasteboard.co/nbX8uLaCV7Ni.png

**Comment by lazkopat3718** [comment]
https://pasteboard.co/0q9o3CQXc7Rg.png

**Comment by lazkopat3718** [comment]
https://pasteboard.co/FwOU8gKoBBjA.png

**Comment by lazkopat3718** [comment]
https://pasteboard.co/uo2eEEOPvj1G.png mod list ***

**Comment by Darkhax** [comment]
Hello, initially I thought this was a bug related to non-english languages but it seems to display fine for me and is also translated to Turkish. It is likely an issue with another mod you have installed.

![image](https://github.com/user-attachments/assets/c735cfdc-de5b-4d39-b382-3612e1fb6e64)

**Comment by Darkhax** [comment]
I spoke too soon, I found the issue and will fix it for you soon.

**Comment by Darkhax** [comment]
Please update to [21.1.2](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/all?version=1.21.1) when it is available on CurseForge and let me know if it fixes your issue.

**Comment by lazkopat3718** [comment]
solved so thanks bro
