### ISSUE TITLE
[QUESTION] No 1.21? (1.21.0)

### ISSUE THREAD

**Issue by DuckSleazzy** [Darkhax-Minecraft/Enchantment-Descriptions#255]
### Question

Basically the title. Was waiting fo 1.21 and then boom, 1.21.1

The server I play on is 1.21

**Comment by Darkhax** [comment]
Hello, the base version of Minecraft 1.21 has some vulnerabilities and should no longer be used or supported. The 1.21.1 patch was a security update that should not break any mods or plugins.

**Comment by xFrah** [comment]
Still, a lot of mods remain on 1.21, so would you be so kind to release a 1.21 version?
