### ISSUE TITLE
Tool tip displays under non-enchanted things

### ISSUE THREAD

**Issue by Wdavery** [Darkhax-Minecraft/Enchantment-Descriptions#26]
When enabling the config option to have tool tips display for more than just books, the "press left shift for enchantment descriptions" appears on every item.

**Comment by Darkhax** [comment]
Thanks for the bug report, this will be fixed shortly.

**Comment by Wdavery** [comment]
Tried the new version, works great. Exactly how I was hoping. Thanks for the incredibly fast fix!
