### ISSUE TITLE
[FEEDBACK] support version 1.21

### ISSUE THREAD

**Issue by MR-pinguin** [Darkhax-Minecraft/Enchantment-Descriptions#264]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Feedback

I think that it's sad that you update the mod to 1.21.1 but not 1.21 :( 
And I can't add _enchantment descriptions_ to my modpack, I use a mod that add many enchants and without any description it's very hard to understand what they do (mod : _enchancement_)
thx :)

**Comment by Pixie-Kitty** [comment]
I agree! I wish this had a 1.21 version. Most of the mods I run are only updated barley to 1.21. I'm in need of this mod because some of them have new enchantments, and I'm stumped on what they do without this mod.

**Comment by Darkhax** [comment]
Hello, I've said this in a few places already but unfortunately I have no plans to support the base 1.21 version of Minecraft. The original 1.21 has some major stability/security issues and was quickly replaced by 1.21.1. It's considered best practice for modders to not support this version in favor of 1.21.1 or newer versions.
