### ISSUE TITLE
add lang es_ar.json

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Enchantment-Descriptions#27]
Hello, I play with the language es-ar, if they add it it would be very good!

**Comment by Darkhax** [comment]
Hello, I would like to add support but I do not speak the language. All translations have been sent by community members who want to help out.

**Comment by Gexur** [comment]
Just copy the es-es.json and rename it to es-ar (Spanish from Spain to Spanish from Argentina)

**Comment by ghost** [comment]
[es_ar.zip](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/4400521/es_ar.zip)

**Comment by Darkhax** [comment]
I don't really think it works that way, but if it makes you happy lol. It's on the next CF build.
