### ISSUE TITLE
Adding / Modifying Descriptions via Config

### ISSUE THREAD

**Issue by Cynan** [Darkhax-Minecraft/Enchantment-Descriptions#30]
Any chance the mod could allow for adding / modifying descriptions via the config to handle mods or versions of mods where they haven't added descriptions to their language files?   

Mod is great but painful seeing enchantment.xxx.xxx.desc every now and again.

**Comment by Darkhax** [comment]
It uses translatable text which is not possible to define through configs. You can use other mods like CraftTweaker, OpenLoader, and ResourceLoader to add custom descriptions. You can also just ask the mod authors (including me) to add native support for those enchantments.

**Comment by Cynan** [comment]
Thanks.  I've logged an issue there.  For Charm -> https://www.curseforge.com/minecraft/mc-mods/charm
