### ISSUE TITLE
Why is a core mod a dependency if it works without it?

### ISSUE THREAD

**Issue by MadDog443** [Darkhax-Minecraft/Enchantment-Descriptions#31]
So your core mod "Bookshelf" is set as a dependency, but I can run "Enchantment Descriptions" 1.12.2 without it. Why is this a thing?

**Comment by Darkhax** [comment]
Bookshelf is now used for detecting the mod which adds an enchantment to the game, which is then used for displaying the name of that mod in the tooltip. Also Bookshelf is not a core mod, that term is specifically for mods which use ASM or Mixin to tamper with the vanilla code.

**Comment by MadDog443** [comment]
Thank you for the explanation.
