### ISSUE TITLE
Keybind Option

### ISSUE THREAD

**Issue by Th3DocCroc** [Darkhax-Minecraft/Enchantment-Descriptions#42]
Could you maybe add a keybind option for the descriptions?

I change sneak to mouse 4 button, and holding it down doesn't work to see descriptions.

**Comment by Th3DocCroc** [comment]
I'm a little slow, sorry. I just found the config

**Comment by Darkhax** [comment]
Hey there, this mod actually doesn't have a keybind but it's something I would like to consider for a future update. I am going to keep this issue open until I add that.
