### ISSUE TITLE
Text doesn't wrap back

### ISSUE THREAD

**Issue by PassyFox** [Darkhax-Minecraft/Enchantment-Descriptions#44]
some text is way too long in one sentence and therefore the text goes outside the visible screen. is it possible to have it wrap shorter or automaticly

**Comment by Darkhax** [comment]
Is this with Forge or Fabric? When using Forge tooltip text will wrap automatically, when using Fabric you need an additional mod that adds it because they don't include it by default.

**Comment by PassyFox** [comment]
this is within fabric, what mod needs to be installed

**Comment by Darkhax** [comment]
There are a bunch of them, but this is the one I tested with. https://www.curseforge.com/minecraft/mc-mods/tooltipfix
