### ISSUE TITLE
RandomEnchants Mod Support? [Suggestion/Enhancement]

### ISSUE THREAD

**Issue by Coraline77447** [Darkhax-Minecraft/Enchantment-Descriptions#45]
Hi, Can you add mod support for RandomEnchants mod? You probably know what RandomEnchants mod is but what it is is a mod that adds more enchantments to the game. also every single time I find a ruined nether portal with enchanted golden armor (and maybe tools as well) that there's this one enchantment called Netherproof and in the tooltip its descrioption is litterly it's file name (I think it's like this; randomenchants:nether_proof). Please and thank you.

**Comment by Darkhax** [comment]
RandomEnchantments already adds support on their own, they just forgot to update it with the new enchantments.

**Comment by Coraline77447** [comment]
Ok but how about Enchanting Fever? Is that mod already supported by Enchantment Descriptions or they already have support but they've forgotten about updating something on their end?
