### ISSUE TITLE
Minecraft Dungeons Gear Descriptions

### ISSUE THREAD

**Issue by iep1000** [Darkhax-Minecraft/Enchantment-Descriptions#46]
So the Minecraft Dungeons mod say it is compatible with this mod. But when I try to run them together it doesn't work. It only gives me the Minecraft item tag ([screenshot](https://ibb.co/Ch6NVCY)) for the dungeons gear. It does give me the vanilla enchantments descriptions, which I don't really need. This is running alongside AOF3.

**Comment by Darkhax** [comment]
It looks like you're using [MC Dungeons Weapons](https://www.curseforge.com/minecraft/mc-mods/mcdw) which does not have enchantment description support. The [Dungeons Gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear) mod does have support though. If you look in the tooltip the modid is mcdw which is the first mod.
