### ISSUE TITLE
Support for Apotheosis Mod

### ISSUE THREAD

**Issue by MrTailson** [Darkhax-Minecraft/Enchantment-Descriptions#49]
Could you add support for Apotheosis mod and their enchantments?

Apotheosis: https://www.curseforge.com/minecraft/mc-mods/apotheosis

**Comment by Darkhax** [comment]
Apotheosis has built in support for this mod already. https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/resources/assets/apotheosis/lang/en_us.json#L370

**Comment by MrTailson** [comment]
My bad. Sorry.
