### ISSUE TITLE
Polish translation.

### ISSUE THREAD

**Issue by K0-RR** [Darkhax-Minecraft/Enchantment-Descriptions#50]
I would like to contribute by adding it but how? So far I only translated by Poeditor and Crowdin. Here I suppose I need to make a pr?

**Comment by Darkhax** [comment]
Hello, yes you would need to make a Pull Request. The general steps would look something like this.

1. Create a Fork of the original repo.
2. Create a new JSON file for the lang, this can be done through GitHub's web interface.
3. Copy the en_us.json file and change the values to the polish ones. The save the file.
4. Come back to this repo and click on pull requests, then open a new one.
5. Look for the "Compare Across Forks" option, clicking this will allow you to select your Forked version of the repo when making the PR.

**Comment by K0-RR** [comment]
https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/pull/51
