### ISSUE TITLE
(Enhancement) JEI Enchantment Info compatibility

### ISSUE THREAD

**Issue by skyjay1** [Darkhax-Minecraft/Enchantment-Descriptions#52]
Suggestion:
Allow the enchantment description key to be in the format `"enchantment.[MOD_ID].[ENCHENTMENT_REGISTRY_NAME].description"` as well as the current supported format of `.desc`. This will allow any mod that has JEI Enchantment Info compatibility to automatically be compatible with Enchantment Descriptions.
Source: [https://github.com/Phylogeny/JEIEnchantmentInfo#readme](https://github.com/Phylogeny/JEIEnchantmentInfo#readme)

**Comment by Darkhax** [comment]
I've implemented partial support for it in [7.0.7](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3276267). I would recommend that mod authors continue to use the `.desc` suffix though. This key format has been widely used by several mods and dates back to roughly the same time enchantments were added to the game.
