### ISSUE TITLE
[Fabric] Text out of window

### ISSUE THREAD

**Issue by Nethet** [Darkhax-Minecraft/Enchantment-Descriptions#60]
Hello,
I got a little issue in the latest fabric version 1.16.5, 2.0.2. When you have a guiScale:0 or Auto, the text is no longer fully readable because it gets out of bound (see screenshot below):

![bug enchant](https://user-images.githubusercontent.com/38501555/115711000-49d20800-a373-11eb-9357-e6a2889af7f9.PNG)

There should be a character limit, for me in auto it's around 42.
Thank you in advance

**Comment by Darkhax** [comment]
Hello,

This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).
