### ISSUE TITLE
Support for Colds: Enchants

### ISSUE THREAD

**Issue by NixityNull** [Darkhax-Minecraft/Enchantment-Descriptions#65]
https://www.curseforge.com/minecraft/mc-mods/colds-enchants-forge does not yet have support of this mod and while I asked the mod author on his page if he would be making compatabilities it seems he may be to busy to as he has not answered since.

**Comment by MickeyMouseYT** [comment]
[Enchant-Descriptions_Colds_Enchants.zip](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/6686582/Enchant-Descriptions_Colds_Enchants.zip)

No problem ;)

**Comment by Darkhax** [comment]
Thanks for the help, it's now been added.
