### ISSUE TITLE
[fabric] Description too long for several enchantment books

### ISSUE THREAD

**Issue by jocker-il** [Darkhax-Minecraft/Enchantment-Descriptions#66]
So far I found two who's description is making the display too long thus losing the name of the enchantment (I extrapolated from the part of the description that I could see which enchantment it is)

- Infinity
- Aqua Affinity

**Comment by Darkhax** [comment]
Hello,

This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).
