### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by gcaraman** [Darkhax-Minecraft/Enchantment-Descriptions#67]
There are some long descriptions which causes part of the tooltip to go offscreen.
Could you please implement a word wrap feature for the description once it passes a certain char length?

**Comment by Darkhax** [comment]
Duplicate of #60 and #66. 

This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).
