### ISSUE TITLE
Support for travel anchors

### ISSUE THREAD

**Issue by MickeyMouseYT** [Darkhax-Minecraft/Enchantment-Descriptions#71]
https://www.curseforge.com/minecraft/mc-mods/travel-anchors

[Enchant-Descriptions_Travel_Anchors.zip](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/6686598/Enchant-Descriptions_Travel_Anchors.zip)

Thank you 👍

**Comment by Darkhax** [comment]
Thanks for the help.
