### ISSUE TITLE
Enchantments go off the screen

### ISSUE THREAD

**Issue by HoodBlah** [Darkhax-Minecraft/Enchantment-Descriptions#77]
Fabric 1.17.1, when hovering over an enchantment the description and name go off the side of the screen if its long.

**Comment by Darkhax** [comment]
Hello,

This is a vanilla bug. On Forge the bug is fixed by Forge so nobody notices it. On Fabric you will need a 3rd party mod to fix the bug. For example [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix).

Duplicate of #60
