### ISSUE TITLE
Enchantments report wrong creator modid

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Darkhax-Minecraft/Enchantment-Descriptions#8]
Your format specifies that the modid comes as the second argument in the description key `enchantment.modid.name.desc`, but when you display the "Added by: x" section, it is using the third argument, the enchantment name.  

It does this for vanilla enchantments as well.

**Comment by Shadows-of-Fire** [comment]
https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/blob/master/src/main/java/net/darkhax/enchdesc/client/TooltipHandler.java#L116
Should be getNamespace

**Comment by darkhax** [comment]
Whoops, thanks for the report.
