### ISSUE TITLE
1.17 Forge

### ISSUE THREAD

**Issue by WiredSamurai** [Darkhax-Minecraft/Enchantment-Descriptions#82]
I hate to be a bother as I am sure you are getting plenty of annoyances such as this; However I still can't help but wonder how the update is coming along for **1.17 Forge**. Please take your time at replying and updating, just don't see where I could view update's progress otherwise. Thanks for your amazing work! Keep it up. <3

**Comment by Darkhax** [comment]
I've released a basic backport for 1.17 but I can't promise it will receive continued support and updates.

[Forge 1.17.1](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3576541)

[Fabric 1.17.1](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3576540)
