### ISSUE TITLE
config for fabric

### ISSUE THREAD

**Issue by basocjk** [Darkhax-Minecraft/Enchantment-Descriptions#83]
i want it to show up on weapons and tools too. i have read #62 , and I understand why it wasn't done yet.

i'll just leave it here so I'll get notified when it gets implemented.

no rush devs. thank you.

**Comment by Darkhax** [comment]
In newer versions I have made some pretty big changes to how the mod works and have removed config options from Forge as well. Virtually everyone likes seeing descriptions on all applicable items so this is now the new default behavior of the mod. 

I may re-add config options in the future, but a lot of the old options are specific to the old system and don't really make sense here.
