### ISSUE TITLE
crash on loading (v 1.17.1)

### ISSUE THREAD

**Issue by IamSweetie** [Darkhax-Minecraft/Enchantment-Descriptions#92]
I added the file EnchantmentDescriptions-Forge-1.17.1-8.17.1.jar to my current modpack and it had class loading errors on startup - poss a problem with compatibility with the flywheel mod - I've also logged the issue on their github 
[crash-2021-12-22_20.51.29-fml.txt](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/7770916/crash-2021-12-22_20.51.29-fml.txt)

**Comment by Darkhax** [comment]
This issue has nothing to do with Flywheel. The mod was compiled with Java 17 rather than Java 16 so users who have not updated will have issues. I've put out a new version that is Java16 compatible. See 8.17.2.

**Comment by Old-Man-D** [comment]
I was helping another person troubleshoot their modpack, and I think I ran into this issue.  The log shows version 8.17.2, yet still seems to be referencing java 17 I think.  removing the mod cleared up the crash for them.  
[latest (3).log](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/files/8455197/latest.3.log)

**Comment by Darkhax** [comment]
@Old-Man-D Thanks for following up on this issue. It looks like some compiler options were still set to Java 17. I've put out a new alpha and would appreciate it if you could try this update out. 

Fabric - https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3740894

Forge - https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions/files/3740895
