### ISSUE TITLE
"Latest Release Version"

### ISSUE THREAD

**Issue by hstheperson** [Darkhax-Minecraft/Enchantment-Descriptions#94]
For some reason, the latest version is marked as EnchantmentDescriptions-Forge-1.18.1-9.0.4.jar on the Curseforge page, despite that not being the case.
![image](https://user-images.githubusercontent.com/91855262/147796754-6defc0e8-60e5-4c13-8e87-0fc590a23a8c.png)
This causes the "Update" button to install 9.0.4, rather than the actual latest version. I first observed this with the 9.0.5 release.
![image](https://user-images.githubusercontent.com/91855262/147796864-ef42a34b-893a-48dc-b14a-0e7f93d3be07.png)
![image](https://user-images.githubusercontent.com/91855262/147796883-4254c63c-355f-4b50-ab69-92e0a433fbf3.png)

**Comment by Darkhax** [comment]
Thanks for letting me know about this. CurseForge only promotes files marked as "Release" for their "Latest Release" section so it makes sense that 9.0.7 is not displayed. 9.0.5 on the other hand should be displayed and seems to be an issue CurseForge's system. This isn't an issue mod authors can fix and I will reach out to the CurseForge team to get it resolved.

**Comment by tomwolfgang** [comment]
Hey @Darkhax this looks like a bug on our App's side.
We'll look into it
